# Form implementation generated from reading ui file 'FolderOrdnung.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(497, 571)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.BtnDetectSubfolders = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnDetectSubfolders.sizePolicy().hasHeightForWidth())
        self.BtnDetectSubfolders.setSizePolicy(sizePolicy)
        self.BtnDetectSubfolders.setMinimumSize(QtCore.QSize(150, 75))
        self.BtnDetectSubfolders.setObjectName("BtnDetectSubfolders")
        self.gridLayout.addWidget(self.BtnDetectSubfolders, 2, 0, 1, 1)
        self.BtnSelectOrdnung = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnSelectOrdnung.sizePolicy().hasHeightForWidth())
        self.BtnSelectOrdnung.setSizePolicy(sizePolicy)
        self.BtnSelectOrdnung.setMinimumSize(QtCore.QSize(150, 75))
        self.BtnSelectOrdnung.setObjectName("BtnSelectOrdnung")
        self.gridLayout.addWidget(self.BtnSelectOrdnung, 0, 0, 1, 1)
        self.BtnSelMulFolders = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnSelMulFolders.sizePolicy().hasHeightForWidth())
        self.BtnSelMulFolders.setSizePolicy(sizePolicy)
        self.BtnSelMulFolders.setMinimumSize(QtCore.QSize(150, 75))
        self.BtnSelMulFolders.setObjectName("BtnSelMulFolders")
        self.gridLayout.addWidget(self.BtnSelMulFolders, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BtnDetectSubfolders.setText(_translate("MainWindow", "Detect Subfolders"))
        self.BtnSelectOrdnung.setText(_translate("MainWindow", "Select Folders"))
        self.BtnSelMulFolders.setText(_translate("MainWindow", "Select Multiple Folders"))
